version: 2

jobs:
  build:
    working_directory: ~/dynalock

    docker:
      - image: circleci/ruby:2.4
        environment:
          - DYNAMODB_CREATE_TEST_TABLE: 1
          - DYNAMODB_ENDPOINT: "http://localhost:8000"
      - image: amazon/dynamodb-local

    steps:
      - checkout

      # Dependencies
      - restore_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Test
      - run: bundle exec rake test
